//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DAL.ExcelProcessor
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AVEB_ESEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AVEB_ESEntities object using the connection string found in the 'AVEB_ESEntities' section of the application configuration file.
        /// </summary>
        public AVEB_ESEntities() : base("name=AVEB_ESEntities", "AVEB_ESEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AVEB_ESEntities object.
        /// </summary>
        public AVEB_ESEntities(string connectionString) : base(connectionString, "AVEB_ESEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AVEB_ESEntities object.
        /// </summary>
        public AVEB_ESEntities(EntityConnection connection) : base(connection, "AVEB_ESEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GEISIntermediaErratas> GEISIntermediaErratas
        {
            get
            {
                if ((_GEISIntermediaErratas == null))
                {
                    _GEISIntermediaErratas = base.CreateObjectSet<GEISIntermediaErratas>("GEISIntermediaErratas");
                }
                return _GEISIntermediaErratas;
            }
        }
        private ObjectSet<GEISIntermediaErratas> _GEISIntermediaErratas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GEISIntermediaPacks> GEISIntermediaPacks
        {
            get
            {
                if ((_GEISIntermediaPacks == null))
                {
                    _GEISIntermediaPacks = base.CreateObjectSet<GEISIntermediaPacks>("GEISIntermediaPacks");
                }
                return _GEISIntermediaPacks;
            }
        }
        private ObjectSet<GEISIntermediaPacks> _GEISIntermediaPacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GEISIntermediaPacksHidden> GEISIntermediaPacksHidden
        {
            get
            {
                if ((_GEISIntermediaPacksHidden == null))
                {
                    _GEISIntermediaPacksHidden = base.CreateObjectSet<GEISIntermediaPacksHidden>("GEISIntermediaPacksHidden");
                }
                return _GEISIntermediaPacksHidden;
            }
        }
        private ObjectSet<GEISIntermediaPacksHidden> _GEISIntermediaPacksHidden;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<promoSmartClub> promoSmartClub
        {
            get
            {
                if ((_promoSmartClub == null))
                {
                    _promoSmartClub = base.CreateObjectSet<promoSmartClub>("promoSmartClub");
                }
                return _promoSmartClub;
            }
        }
        private ObjectSet<promoSmartClub> _promoSmartClub;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GEISIntermediaErratas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGEISIntermediaErratas(GEISIntermediaErratas gEISIntermediaErratas)
        {
            base.AddObject("GEISIntermediaErratas", gEISIntermediaErratas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GEISIntermediaPacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGEISIntermediaPacks(GEISIntermediaPacks gEISIntermediaPacks)
        {
            base.AddObject("GEISIntermediaPacks", gEISIntermediaPacks);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GEISIntermediaPacksHidden EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGEISIntermediaPacksHidden(GEISIntermediaPacksHidden gEISIntermediaPacksHidden)
        {
            base.AddObject("GEISIntermediaPacksHidden", gEISIntermediaPacksHidden);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the promoSmartClub EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopromoSmartClub(promoSmartClub promoSmartClub)
        {
            base.AddObject("promoSmartClub", promoSmartClub);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AVEB_ESModel", Name="GEISIntermediaErratas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GEISIntermediaErratas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GEISIntermediaErratas object.
        /// </summary>
        /// <param name="itemName">Initial value of the ItemName property.</param>
        public static GEISIntermediaErratas CreateGEISIntermediaErratas(global::System.String itemName)
        {
            GEISIntermediaErratas gEISIntermediaErratas = new GEISIntermediaErratas();
            gEISIntermediaErratas.ItemName = itemName;
            return gEISIntermediaErratas;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                if (_ItemName != value)
                {
                    OnItemNameChanging(value);
                    ReportPropertyChanging("ItemName");
                    _ItemName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ItemName");
                    OnItemNameChanged();
                }
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReferenciaPack
        {
            get
            {
                return _ReferenciaPack;
            }
            set
            {
                OnReferenciaPackChanging(value);
                ReportPropertyChanging("ReferenciaPack");
                _ReferenciaPack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReferenciaPack");
                OnReferenciaPackChanged();
            }
        }
        private global::System.String _ReferenciaPack;
        partial void OnReferenciaPackChanging(global::System.String value);
        partial void OnReferenciaPackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombrePack
        {
            get
            {
                return _NombrePack;
            }
            set
            {
                OnNombrePackChanging(value);
                ReportPropertyChanging("NombrePack");
                _NombrePack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombrePack");
                OnNombrePackChanged();
            }
        }
        private global::System.String _NombrePack;
        partial void OnNombrePackChanging(global::System.String value);
        partial void OnNombrePackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemDescription
        {
            get
            {
                return _ItemDescription;
            }
            set
            {
                OnItemDescriptionChanging(value);
                ReportPropertyChanging("ItemDescription");
                _ItemDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemDescription");
                OnItemDescriptionChanged();
            }
        }
        private global::System.String _ItemDescription;
        partial void OnItemDescriptionChanging(global::System.String value);
        partial void OnItemDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Colaborador
        {
            get
            {
                return _Colaborador;
            }
            set
            {
                OnColaboradorChanging(value);
                ReportPropertyChanging("Colaborador");
                _Colaborador = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Colaborador");
                OnColaboradorChanged();
            }
        }
        private global::System.String _Colaborador;
        partial void OnColaboradorChanging(global::System.String value);
        partial void OnColaboradorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comunidad
        {
            get
            {
                return _Comunidad;
            }
            set
            {
                OnComunidadChanging(value);
                ReportPropertyChanging("Comunidad");
                _Comunidad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comunidad");
                OnComunidadChanged();
            }
        }
        private global::System.String _Comunidad;
        partial void OnComunidadChanging(global::System.String value);
        partial void OnComunidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provincia
        {
            get
            {
                return _Provincia;
            }
            set
            {
                OnProvinciaChanging(value);
                ReportPropertyChanging("Provincia");
                _Provincia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Provincia");
                OnProvinciaChanged();
            }
        }
        private global::System.String _Provincia;
        partial void OnProvinciaChanging(global::System.String value);
        partial void OnProvinciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pagina
        {
            get
            {
                return _Pagina;
            }
            set
            {
                OnPaginaChanging(value);
                ReportPropertyChanging("Pagina");
                _Pagina = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pagina");
                OnPaginaChanged();
            }
        }
        private global::System.String _Pagina;
        partial void OnPaginaChanging(global::System.String value);
        partial void OnPaginaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Errata
        {
            get
            {
                return _Errata;
            }
            set
            {
                OnErrataChanging(value);
                ReportPropertyChanging("Errata");
                _Errata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Errata");
                OnErrataChanged();
            }
        }
        private global::System.String _Errata;
        partial void OnErrataChanging(global::System.String value);
        partial void OnErrataChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AVEB_ESModel", Name="GEISIntermediaPacks")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GEISIntermediaPacks : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GEISIntermediaPacks object.
        /// </summary>
        /// <param name="counter">Initial value of the Counter property.</param>
        public static GEISIntermediaPacks CreateGEISIntermediaPacks(global::System.Int32 counter)
        {
            GEISIntermediaPacks gEISIntermediaPacks = new GEISIntermediaPacks();
            gEISIntermediaPacks.Counter = counter;
            return gEISIntermediaPacks;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Counter
        {
            get
            {
                return _Counter;
            }
            set
            {
                if (_Counter != value)
                {
                    OnCounterChanging(value);
                    ReportPropertyChanging("Counter");
                    _Counter = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Counter");
                    OnCounterChanged();
                }
            }
        }
        private global::System.Int32 _Counter;
        partial void OnCounterChanging(global::System.Int32 value);
        partial void OnCounterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemCode
        {
            get
            {
                return _ItemCode;
            }
            set
            {
                OnItemCodeChanging(value);
                ReportPropertyChanging("ItemCode");
                _ItemCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemCode");
                OnItemCodeChanged();
            }
        }
        private global::System.String _ItemCode;
        partial void OnItemCodeChanging(global::System.String value);
        partial void OnItemCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                OnItemNameChanging(value);
                ReportPropertyChanging("ItemName");
                _ItemName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemName");
                OnItemNameChanged();
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemNameEpack
        {
            get
            {
                return _ItemNameEpack;
            }
            set
            {
                OnItemNameEpackChanging(value);
                ReportPropertyChanging("ItemNameEpack");
                _ItemNameEpack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemNameEpack");
                OnItemNameEpackChanged();
            }
        }
        private global::System.String _ItemNameEpack;
        partial void OnItemNameEpackChanging(global::System.String value);
        partial void OnItemNameEpackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemDescription
        {
            get
            {
                return _ItemDescription;
            }
            set
            {
                OnItemDescriptionChanging(value);
                ReportPropertyChanging("ItemDescription");
                _ItemDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemDescription");
                OnItemDescriptionChanged();
            }
        }
        private global::System.String _ItemDescription;
        partial void OnItemDescriptionChanging(global::System.String value);
        partial void OnItemDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TCode
        {
            get
            {
                return _TCode;
            }
            set
            {
                OnTCodeChanging(value);
                ReportPropertyChanging("TCode");
                _TCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TCode");
                OnTCodeChanged();
            }
        }
        private global::System.String _TCode;
        partial void OnTCodeChanging(global::System.String value);
        partial void OnTCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArticleCode
        {
            get
            {
                return _ArticleCode;
            }
            set
            {
                OnArticleCodeChanging(value);
                ReportPropertyChanging("ArticleCode");
                _ArticleCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArticleCode");
                OnArticleCodeChanged();
            }
        }
        private global::System.String _ArticleCode;
        partial void OnArticleCodeChanging(global::System.String value);
        partial void OnArticleCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pax_C
        {
            get
            {
                return _Pax_C;
            }
            set
            {
                OnPax_CChanging(value);
                ReportPropertyChanging("Pax_C");
                _Pax_C = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pax_C");
                OnPax_CChanged();
            }
        }
        private global::System.String _Pax_C;
        partial void OnPax_CChanging(global::System.String value);
        partial void OnPax_CChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ValidityDate
        {
            get
            {
                return _ValidityDate;
            }
            set
            {
                OnValidityDateChanging(value);
                ReportPropertyChanging("ValidityDate");
                _ValidityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidityDate");
                OnValidityDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ValidityDate;
        partial void OnValidityDateChanging(Nullable<global::System.DateTime> value);
        partial void OnValidityDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidityDateText
        {
            get
            {
                return _ValidityDateText;
            }
            set
            {
                OnValidityDateTextChanging(value);
                ReportPropertyChanging("ValidityDateText");
                _ValidityDateText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidityDateText");
                OnValidityDateTextChanged();
            }
        }
        private global::System.String _ValidityDateText;
        partial void OnValidityDateTextChanging(global::System.String value);
        partial void OnValidityDateTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescripcionCorta
        {
            get
            {
                return _DescripcionCorta;
            }
            set
            {
                OnDescripcionCortaChanging(value);
                ReportPropertyChanging("DescripcionCorta");
                _DescripcionCorta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescripcionCorta");
                OnDescripcionCortaChanged();
            }
        }
        private global::System.String _DescripcionCorta;
        partial void OnDescripcionCortaChanging(global::System.String value);
        partial void OnDescripcionCortaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescripcionLarga
        {
            get
            {
                return _DescripcionLarga;
            }
            set
            {
                OnDescripcionLargaChanging(value);
                ReportPropertyChanging("DescripcionLarga");
                _DescripcionLarga = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescripcionLarga");
                OnDescripcionLargaChanged();
            }
        }
        private global::System.String _DescripcionLarga;
        partial void OnDescripcionLargaChanging(global::System.String value);
        partial void OnDescripcionLargaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgURL
        {
            get
            {
                return _imgURL;
            }
            set
            {
                OnimgURLChanging(value);
                ReportPropertyChanging("imgURL");
                _imgURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgURL");
                OnimgURLChanged();
            }
        }
        private global::System.String _imgURL;
        partial void OnimgURLChanging(global::System.String value);
        partial void OnimgURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgPromoURL
        {
            get
            {
                return _imgPromoURL;
            }
            set
            {
                OnimgPromoURLChanging(value);
                ReportPropertyChanging("imgPromoURL");
                _imgPromoURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgPromoURL");
                OnimgPromoURLChanged();
            }
        }
        private global::System.String _imgPromoURL;
        partial void OnimgPromoURLChanging(global::System.String value);
        partial void OnimgPromoURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgURLepack
        {
            get
            {
                return _imgURLepack;
            }
            set
            {
                OnimgURLepackChanging(value);
                ReportPropertyChanging("imgURLepack");
                _imgURLepack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgURLepack");
                OnimgURLepackChanged();
            }
        }
        private global::System.String _imgURLepack;
        partial void OnimgURLepackChanging(global::System.String value);
        partial void OnimgURLepackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RetailPrice
        {
            get
            {
                return _RetailPrice;
            }
            set
            {
                OnRetailPriceChanging(value);
                ReportPropertyChanging("RetailPrice");
                _RetailPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RetailPrice");
                OnRetailPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _RetailPrice;
        partial void OnRetailPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnRetailPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SpecialPrice
        {
            get
            {
                return _SpecialPrice;
            }
            set
            {
                OnSpecialPriceChanging(value);
                ReportPropertyChanging("SpecialPrice");
                _SpecialPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpecialPrice");
                OnSpecialPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _SpecialPrice;
        partial void OnSpecialPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnSpecialPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RetailPriceEPack
        {
            get
            {
                return _RetailPriceEPack;
            }
            set
            {
                OnRetailPriceEPackChanging(value);
                ReportPropertyChanging("RetailPriceEPack");
                _RetailPriceEPack = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RetailPriceEPack");
                OnRetailPriceEPackChanged();
            }
        }
        private Nullable<global::System.Decimal> _RetailPriceEPack;
        partial void OnRetailPriceEPackChanging(Nullable<global::System.Decimal> value);
        partial void OnRetailPriceEPackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuiaOnlineURL
        {
            get
            {
                return _GuiaOnlineURL;
            }
            set
            {
                OnGuiaOnlineURLChanging(value);
                ReportPropertyChanging("GuiaOnlineURL");
                _GuiaOnlineURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuiaOnlineURL");
                OnGuiaOnlineURLChanged();
            }
        }
        private global::System.String _GuiaOnlineURL;
        partial void OnGuiaOnlineURLChanging(global::System.String value);
        partial void OnGuiaOnlineURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductosAsociados
        {
            get
            {
                return _ProductosAsociados;
            }
            set
            {
                OnProductosAsociadosChanging(value);
                ReportPropertyChanging("ProductosAsociados");
                _ProductosAsociados = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductosAsociados");
                OnProductosAsociadosChanged();
            }
        }
        private global::System.String _ProductosAsociados;
        partial void OnProductosAsociadosChanging(global::System.String value);
        partial void OnProductosAsociadosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mundo
        {
            get
            {
                return _Mundo;
            }
            set
            {
                OnMundoChanging(value);
                ReportPropertyChanging("Mundo");
                _Mundo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mundo");
                OnMundoChanged();
            }
        }
        private global::System.String _Mundo;
        partial void OnMundoChanging(global::System.String value);
        partial void OnMundoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> ShowBuyButton
        {
            get
            {
                return _ShowBuyButton;
            }
            set
            {
                OnShowBuyButtonChanging(value);
                ReportPropertyChanging("ShowBuyButton");
                _ShowBuyButton = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowBuyButton");
                OnShowBuyButtonChanged();
            }
        }
        private Nullable<global::System.Byte> _ShowBuyButton;
        partial void OnShowBuyButtonChanging(Nullable<global::System.Byte> value);
        partial void OnShowBuyButtonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumExperiencias
        {
            get
            {
                return _NumExperiencias;
            }
            set
            {
                OnNumExperienciasChanging(value);
                ReportPropertyChanging("NumExperiencias");
                _NumExperiencias = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumExperiencias");
                OnNumExperienciasChanged();
            }
        }
        private Nullable<global::System.Int32> _NumExperiencias;
        partial void OnNumExperienciasChanging(Nullable<global::System.Int32> value);
        partial void OnNumExperienciasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Experiencias
        {
            get
            {
                return _Experiencias;
            }
            set
            {
                OnExperienciasChanging(value);
                ReportPropertyChanging("Experiencias");
                _Experiencias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Experiencias");
                OnExperienciasChanged();
            }
        }
        private global::System.String _Experiencias;
        partial void OnExperienciasChanging(global::System.String value);
        partial void OnExperienciasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SETitle
        {
            get
            {
                return _SETitle;
            }
            set
            {
                OnSETitleChanging(value);
                ReportPropertyChanging("SETitle");
                _SETitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SETitle");
                OnSETitleChanged();
            }
        }
        private global::System.String _SETitle;
        partial void OnSETitleChanging(global::System.String value);
        partial void OnSETitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEDescription
        {
            get
            {
                return _SEDescription;
            }
            set
            {
                OnSEDescriptionChanging(value);
                ReportPropertyChanging("SEDescription");
                _SEDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SEDescription");
                OnSEDescriptionChanged();
            }
        }
        private global::System.String _SEDescription;
        partial void OnSEDescriptionChanging(global::System.String value);
        partial void OnSEDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEKeywords
        {
            get
            {
                return _SEKeywords;
            }
            set
            {
                OnSEKeywordsChanging(value);
                ReportPropertyChanging("SEKeywords");
                _SEKeywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SEKeywords");
                OnSEKeywordsChanged();
            }
        }
        private global::System.String _SEKeywords;
        partial void OnSEKeywordsChanging(global::System.String value);
        partial void OnSEKeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DescuentoMax
        {
            get
            {
                return _DescuentoMax;
            }
            set
            {
                OnDescuentoMaxChanging(value);
                ReportPropertyChanging("DescuentoMax");
                _DescuentoMax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DescuentoMax");
                OnDescuentoMaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _DescuentoMax;
        partial void OnDescuentoMaxChanging(Nullable<global::System.Decimal> value);
        partial void OnDescuentoMaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String friendlyURL
        {
            get
            {
                return _friendlyURL;
            }
            set
            {
                OnfriendlyURLChanging(value);
                ReportPropertyChanging("friendlyURL");
                _friendlyURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("friendlyURL");
                OnfriendlyURLChanged();
            }
        }
        private global::System.String _friendlyURL;
        partial void OnfriendlyURLChanging(global::System.String value);
        partial void OnfriendlyURLChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AVEB_ESModel", Name="GEISIntermediaPacksHidden")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GEISIntermediaPacksHidden : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GEISIntermediaPacksHidden object.
        /// </summary>
        /// <param name="counter">Initial value of the Counter property.</param>
        public static GEISIntermediaPacksHidden CreateGEISIntermediaPacksHidden(global::System.Int32 counter)
        {
            GEISIntermediaPacksHidden gEISIntermediaPacksHidden = new GEISIntermediaPacksHidden();
            gEISIntermediaPacksHidden.Counter = counter;
            return gEISIntermediaPacksHidden;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Counter
        {
            get
            {
                return _Counter;
            }
            set
            {
                if (_Counter != value)
                {
                    OnCounterChanging(value);
                    ReportPropertyChanging("Counter");
                    _Counter = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Counter");
                    OnCounterChanged();
                }
            }
        }
        private global::System.Int32 _Counter;
        partial void OnCounterChanging(global::System.Int32 value);
        partial void OnCounterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemCode
        {
            get
            {
                return _ItemCode;
            }
            set
            {
                OnItemCodeChanging(value);
                ReportPropertyChanging("ItemCode");
                _ItemCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemCode");
                OnItemCodeChanged();
            }
        }
        private global::System.String _ItemCode;
        partial void OnItemCodeChanging(global::System.String value);
        partial void OnItemCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                OnItemNameChanging(value);
                ReportPropertyChanging("ItemName");
                _ItemName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemName");
                OnItemNameChanged();
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemNameEpack
        {
            get
            {
                return _ItemNameEpack;
            }
            set
            {
                OnItemNameEpackChanging(value);
                ReportPropertyChanging("ItemNameEpack");
                _ItemNameEpack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemNameEpack");
                OnItemNameEpackChanged();
            }
        }
        private global::System.String _ItemNameEpack;
        partial void OnItemNameEpackChanging(global::System.String value);
        partial void OnItemNameEpackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemDescription
        {
            get
            {
                return _ItemDescription;
            }
            set
            {
                OnItemDescriptionChanging(value);
                ReportPropertyChanging("ItemDescription");
                _ItemDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemDescription");
                OnItemDescriptionChanged();
            }
        }
        private global::System.String _ItemDescription;
        partial void OnItemDescriptionChanging(global::System.String value);
        partial void OnItemDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TCode
        {
            get
            {
                return _TCode;
            }
            set
            {
                OnTCodeChanging(value);
                ReportPropertyChanging("TCode");
                _TCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TCode");
                OnTCodeChanged();
            }
        }
        private global::System.String _TCode;
        partial void OnTCodeChanging(global::System.String value);
        partial void OnTCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArticleCode
        {
            get
            {
                return _ArticleCode;
            }
            set
            {
                OnArticleCodeChanging(value);
                ReportPropertyChanging("ArticleCode");
                _ArticleCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArticleCode");
                OnArticleCodeChanged();
            }
        }
        private global::System.String _ArticleCode;
        partial void OnArticleCodeChanging(global::System.String value);
        partial void OnArticleCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pax_C
        {
            get
            {
                return _Pax_C;
            }
            set
            {
                OnPax_CChanging(value);
                ReportPropertyChanging("Pax_C");
                _Pax_C = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pax_C");
                OnPax_CChanged();
            }
        }
        private global::System.String _Pax_C;
        partial void OnPax_CChanging(global::System.String value);
        partial void OnPax_CChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ValidityDate
        {
            get
            {
                return _ValidityDate;
            }
            set
            {
                OnValidityDateChanging(value);
                ReportPropertyChanging("ValidityDate");
                _ValidityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidityDate");
                OnValidityDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ValidityDate;
        partial void OnValidityDateChanging(Nullable<global::System.DateTime> value);
        partial void OnValidityDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidityDateText
        {
            get
            {
                return _ValidityDateText;
            }
            set
            {
                OnValidityDateTextChanging(value);
                ReportPropertyChanging("ValidityDateText");
                _ValidityDateText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidityDateText");
                OnValidityDateTextChanged();
            }
        }
        private global::System.String _ValidityDateText;
        partial void OnValidityDateTextChanging(global::System.String value);
        partial void OnValidityDateTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescripcionCorta
        {
            get
            {
                return _DescripcionCorta;
            }
            set
            {
                OnDescripcionCortaChanging(value);
                ReportPropertyChanging("DescripcionCorta");
                _DescripcionCorta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescripcionCorta");
                OnDescripcionCortaChanged();
            }
        }
        private global::System.String _DescripcionCorta;
        partial void OnDescripcionCortaChanging(global::System.String value);
        partial void OnDescripcionCortaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescripcionLarga
        {
            get
            {
                return _DescripcionLarga;
            }
            set
            {
                OnDescripcionLargaChanging(value);
                ReportPropertyChanging("DescripcionLarga");
                _DescripcionLarga = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescripcionLarga");
                OnDescripcionLargaChanged();
            }
        }
        private global::System.String _DescripcionLarga;
        partial void OnDescripcionLargaChanging(global::System.String value);
        partial void OnDescripcionLargaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgURL
        {
            get
            {
                return _imgURL;
            }
            set
            {
                OnimgURLChanging(value);
                ReportPropertyChanging("imgURL");
                _imgURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgURL");
                OnimgURLChanged();
            }
        }
        private global::System.String _imgURL;
        partial void OnimgURLChanging(global::System.String value);
        partial void OnimgURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgPromoURL
        {
            get
            {
                return _imgPromoURL;
            }
            set
            {
                OnimgPromoURLChanging(value);
                ReportPropertyChanging("imgPromoURL");
                _imgPromoURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgPromoURL");
                OnimgPromoURLChanged();
            }
        }
        private global::System.String _imgPromoURL;
        partial void OnimgPromoURLChanging(global::System.String value);
        partial void OnimgPromoURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgURLePack
        {
            get
            {
                return _imgURLePack;
            }
            set
            {
                OnimgURLePackChanging(value);
                ReportPropertyChanging("imgURLePack");
                _imgURLePack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgURLePack");
                OnimgURLePackChanged();
            }
        }
        private global::System.String _imgURLePack;
        partial void OnimgURLePackChanging(global::System.String value);
        partial void OnimgURLePackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RetailPrice
        {
            get
            {
                return _RetailPrice;
            }
            set
            {
                OnRetailPriceChanging(value);
                ReportPropertyChanging("RetailPrice");
                _RetailPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RetailPrice");
                OnRetailPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _RetailPrice;
        partial void OnRetailPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnRetailPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SpecialPrice
        {
            get
            {
                return _SpecialPrice;
            }
            set
            {
                OnSpecialPriceChanging(value);
                ReportPropertyChanging("SpecialPrice");
                _SpecialPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpecialPrice");
                OnSpecialPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _SpecialPrice;
        partial void OnSpecialPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnSpecialPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RetailPriceEPack
        {
            get
            {
                return _RetailPriceEPack;
            }
            set
            {
                OnRetailPriceEPackChanging(value);
                ReportPropertyChanging("RetailPriceEPack");
                _RetailPriceEPack = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RetailPriceEPack");
                OnRetailPriceEPackChanged();
            }
        }
        private Nullable<global::System.Decimal> _RetailPriceEPack;
        partial void OnRetailPriceEPackChanging(Nullable<global::System.Decimal> value);
        partial void OnRetailPriceEPackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuiaOnlineURL
        {
            get
            {
                return _GuiaOnlineURL;
            }
            set
            {
                OnGuiaOnlineURLChanging(value);
                ReportPropertyChanging("GuiaOnlineURL");
                _GuiaOnlineURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuiaOnlineURL");
                OnGuiaOnlineURLChanged();
            }
        }
        private global::System.String _GuiaOnlineURL;
        partial void OnGuiaOnlineURLChanging(global::System.String value);
        partial void OnGuiaOnlineURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductosAsociados
        {
            get
            {
                return _ProductosAsociados;
            }
            set
            {
                OnProductosAsociadosChanging(value);
                ReportPropertyChanging("ProductosAsociados");
                _ProductosAsociados = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductosAsociados");
                OnProductosAsociadosChanged();
            }
        }
        private global::System.String _ProductosAsociados;
        partial void OnProductosAsociadosChanging(global::System.String value);
        partial void OnProductosAsociadosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mundo
        {
            get
            {
                return _Mundo;
            }
            set
            {
                OnMundoChanging(value);
                ReportPropertyChanging("Mundo");
                _Mundo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mundo");
                OnMundoChanged();
            }
        }
        private global::System.String _Mundo;
        partial void OnMundoChanging(global::System.String value);
        partial void OnMundoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> ShowBuyButton
        {
            get
            {
                return _ShowBuyButton;
            }
            set
            {
                OnShowBuyButtonChanging(value);
                ReportPropertyChanging("ShowBuyButton");
                _ShowBuyButton = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowBuyButton");
                OnShowBuyButtonChanged();
            }
        }
        private Nullable<global::System.Byte> _ShowBuyButton;
        partial void OnShowBuyButtonChanging(Nullable<global::System.Byte> value);
        partial void OnShowBuyButtonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumExperiencias
        {
            get
            {
                return _NumExperiencias;
            }
            set
            {
                OnNumExperienciasChanging(value);
                ReportPropertyChanging("NumExperiencias");
                _NumExperiencias = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumExperiencias");
                OnNumExperienciasChanged();
            }
        }
        private Nullable<global::System.Int32> _NumExperiencias;
        partial void OnNumExperienciasChanging(Nullable<global::System.Int32> value);
        partial void OnNumExperienciasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Experiencias
        {
            get
            {
                return _Experiencias;
            }
            set
            {
                OnExperienciasChanging(value);
                ReportPropertyChanging("Experiencias");
                _Experiencias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Experiencias");
                OnExperienciasChanged();
            }
        }
        private global::System.String _Experiencias;
        partial void OnExperienciasChanging(global::System.String value);
        partial void OnExperienciasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SETitle
        {
            get
            {
                return _SETitle;
            }
            set
            {
                OnSETitleChanging(value);
                ReportPropertyChanging("SETitle");
                _SETitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SETitle");
                OnSETitleChanged();
            }
        }
        private global::System.String _SETitle;
        partial void OnSETitleChanging(global::System.String value);
        partial void OnSETitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEDescription
        {
            get
            {
                return _SEDescription;
            }
            set
            {
                OnSEDescriptionChanging(value);
                ReportPropertyChanging("SEDescription");
                _SEDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SEDescription");
                OnSEDescriptionChanged();
            }
        }
        private global::System.String _SEDescription;
        partial void OnSEDescriptionChanging(global::System.String value);
        partial void OnSEDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEKeywords
        {
            get
            {
                return _SEKeywords;
            }
            set
            {
                OnSEKeywordsChanging(value);
                ReportPropertyChanging("SEKeywords");
                _SEKeywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SEKeywords");
                OnSEKeywordsChanged();
            }
        }
        private global::System.String _SEKeywords;
        partial void OnSEKeywordsChanging(global::System.String value);
        partial void OnSEKeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DescuentoMax
        {
            get
            {
                return _DescuentoMax;
            }
            set
            {
                OnDescuentoMaxChanging(value);
                ReportPropertyChanging("DescuentoMax");
                _DescuentoMax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DescuentoMax");
                OnDescuentoMaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _DescuentoMax;
        partial void OnDescuentoMaxChanging(Nullable<global::System.Decimal> value);
        partial void OnDescuentoMaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String friendlyURL
        {
            get
            {
                return _friendlyURL;
            }
            set
            {
                OnfriendlyURLChanging(value);
                ReportPropertyChanging("friendlyURL");
                _friendlyURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("friendlyURL");
                OnfriendlyURLChanged();
            }
        }
        private global::System.String _friendlyURL;
        partial void OnfriendlyURLChanging(global::System.String value);
        partial void OnfriendlyURLChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AVEB_ESModel", Name="promoSmartClub")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class promoSmartClub : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new promoSmartClub object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static promoSmartClub CreatepromoSmartClub(global::System.Int32 id)
        {
            promoSmartClub promoSmartClub = new promoSmartClub();
            promoSmartClub.ID = id;
            return promoSmartClub;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Promo
        {
            get
            {
                return _ID_Promo;
            }
            set
            {
                OnID_PromoChanging(value);
                ReportPropertyChanging("ID_Promo");
                _ID_Promo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_Promo");
                OnID_PromoChanged();
            }
        }
        private global::System.String _ID_Promo;
        partial void OnID_PromoChanging(global::System.String value);
        partial void OnID_PromoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num_pagina
        {
            get
            {
                return _num_pagina;
            }
            set
            {
                Onnum_paginaChanging(value);
                ReportPropertyChanging("num_pagina");
                _num_pagina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_pagina");
                Onnum_paginaChanged();
            }
        }
        private Nullable<global::System.Int32> _num_pagina;
        partial void Onnum_paginaChanging(Nullable<global::System.Int32> value);
        partial void Onnum_paginaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombreCompany
        {
            get
            {
                return _nombreCompany;
            }
            set
            {
                OnnombreCompanyChanging(value);
                ReportPropertyChanging("nombreCompany");
                _nombreCompany = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombreCompany");
                OnnombreCompanyChanged();
            }
        }
        private global::System.String _nombreCompany;
        partial void OnnombreCompanyChanging(global::System.String value);
        partial void OnnombreCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String universo
        {
            get
            {
                return _universo;
            }
            set
            {
                OnuniversoChanging(value);
                ReportPropertyChanging("universo");
                _universo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("universo");
                OnuniversoChanged();
            }
        }
        private global::System.String _universo;
        partial void OnuniversoChanging(global::System.String value);
        partial void OnuniversoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codPostal
        {
            get
            {
                return _codPostal;
            }
            set
            {
                OncodPostalChanging(value);
                ReportPropertyChanging("codPostal");
                _codPostal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codPostal");
                OncodPostalChanged();
            }
        }
        private global::System.String _codPostal;
        partial void OncodPostalChanging(global::System.String value);
        partial void OncodPostalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String localidad
        {
            get
            {
                return _localidad;
            }
            set
            {
                OnlocalidadChanging(value);
                ReportPropertyChanging("localidad");
                _localidad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("localidad");
                OnlocalidadChanged();
            }
        }
        private global::System.String _localidad;
        partial void OnlocalidadChanging(global::System.String value);
        partial void OnlocalidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String provincia
        {
            get
            {
                return _provincia;
            }
            set
            {
                OnprovinciaChanging(value);
                ReportPropertyChanging("provincia");
                _provincia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("provincia");
                OnprovinciaChanged();
            }
        }
        private global::System.String _provincia;
        partial void OnprovinciaChanging(global::System.String value);
        partial void OnprovinciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comunidadAutonoma
        {
            get
            {
                return _comunidadAutonoma;
            }
            set
            {
                OncomunidadAutonomaChanging(value);
                ReportPropertyChanging("comunidadAutonoma");
                _comunidadAutonoma = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comunidadAutonoma");
                OncomunidadAutonomaChanged();
            }
        }
        private global::System.String _comunidadAutonoma;
        partial void OncomunidadAutonomaChanging(global::System.String value);
        partial void OncomunidadAutonomaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sitioWeb
        {
            get
            {
                return _sitioWeb;
            }
            set
            {
                OnsitioWebChanging(value);
                ReportPropertyChanging("sitioWeb");
                _sitioWeb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sitioWeb");
                OnsitioWebChanged();
            }
        }
        private global::System.String _sitioWeb;
        partial void OnsitioWebChanging(global::System.String value);
        partial void OnsitioWebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opcion1
        {
            get
            {
                return _opcion1;
            }
            set
            {
                Onopcion1Changing(value);
                ReportPropertyChanging("opcion1");
                _opcion1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opcion1");
                Onopcion1Changed();
            }
        }
        private global::System.String _opcion1;
        partial void Onopcion1Changing(global::System.String value);
        partial void Onopcion1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opcion2
        {
            get
            {
                return _opcion2;
            }
            set
            {
                Onopcion2Changing(value);
                ReportPropertyChanging("opcion2");
                _opcion2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opcion2");
                Onopcion2Changed();
            }
        }
        private global::System.String _opcion2;
        partial void Onopcion2Changing(global::System.String value);
        partial void Onopcion2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opcion3
        {
            get
            {
                return _opcion3;
            }
            set
            {
                Onopcion3Changing(value);
                ReportPropertyChanging("opcion3");
                _opcion3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opcion3");
                Onopcion3Changed();
            }
        }
        private global::System.String _opcion3;
        partial void Onopcion3Changing(global::System.String value);
        partial void Onopcion3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opcion4
        {
            get
            {
                return _opcion4;
            }
            set
            {
                Onopcion4Changing(value);
                ReportPropertyChanging("opcion4");
                _opcion4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opcion4");
                Onopcion4Changed();
            }
        }
        private global::System.String _opcion4;
        partial void Onopcion4Changing(global::System.String value);
        partial void Onopcion4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opcion5
        {
            get
            {
                return _opcion5;
            }
            set
            {
                Onopcion5Changing(value);
                ReportPropertyChanging("opcion5");
                _opcion5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opcion5");
                Onopcion5Changed();
            }
        }
        private global::System.String _opcion5;
        partial void Onopcion5Changing(global::System.String value);
        partial void Onopcion5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opcion6
        {
            get
            {
                return _opcion6;
            }
            set
            {
                Onopcion6Changing(value);
                ReportPropertyChanging("opcion6");
                _opcion6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opcion6");
                Onopcion6Changed();
            }
        }
        private global::System.String _opcion6;
        partial void Onopcion6Changing(global::System.String value);
        partial void Onopcion6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String restricciones
        {
            get
            {
                return _restricciones;
            }
            set
            {
                OnrestriccionesChanging(value);
                ReportPropertyChanging("restricciones");
                _restricciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("restricciones");
                OnrestriccionesChanged();
            }
        }
        private global::System.String _restricciones;
        partial void OnrestriccionesChanging(global::System.String value);
        partial void OnrestriccionesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String masVentajas
        {
            get
            {
                return _masVentajas;
            }
            set
            {
                OnmasVentajasChanging(value);
                ReportPropertyChanging("masVentajas");
                _masVentajas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("masVentajas");
                OnmasVentajasChanged();
            }
        }
        private global::System.String _masVentajas;
        partial void OnmasVentajasChanging(global::System.String value);
        partial void OnmasVentajasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String infoPracticas
        {
            get
            {
                return _infoPracticas;
            }
            set
            {
                OninfoPracticasChanging(value);
                ReportPropertyChanging("infoPracticas");
                _infoPracticas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("infoPracticas");
                OninfoPracticasChanged();
            }
        }
        private global::System.String _infoPracticas;
        partial void OninfoPracticasChanging(global::System.String value);
        partial void OninfoPracticasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idFoto
        {
            get
            {
                return _idFoto;
            }
            set
            {
                OnidFotoChanging(value);
                ReportPropertyChanging("idFoto");
                _idFoto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idFoto");
                OnidFotoChanged();
            }
        }
        private global::System.String _idFoto;
        partial void OnidFotoChanging(global::System.String value);
        partial void OnidFotoChanged();

        #endregion
    
    }

    #endregion
    
}
